### ISSUE TITLE
Error: unexpected argument debug

### ISSUE THREAD

**Issue by awesomebytes** [AutonomyLab/freeboard_ros#1]
Hello, I'm trying your very promising node and I've got the following error:

```
~/svn/web_stuff_ws$ rosrun freeboard_ros freeboard_ros.py _host:=127.0.0.1 _port:=3274
Bottle server starting up (using WSGIRefServer(debug=True))...
Listening on http://127.0.0.1:3274/
Hit Ctrl-C to quit.

Shutdown...
Traceback (most recent call last):
  File "/home/sampfeiffer/svn/web_stuff_ws/src/freeboard_ros/scripts/freeboard_ros.py", line 30, in <module>
    main()
  File "/home/sampfeiffer/svn/web_stuff_ws/src/freeboard_ros/scripts/freeboard_ros.py", line 27, in main
    run(host=host, port=port, debug=debug)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 2389, in run
    server.run(app)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 2086, in run
    srv = make_server(self.host, self.port, handler, **self.options)
TypeError: make_server() got an unexpected keyword argument 'debug'
```

Using ubuntu 12.04 I installed bottle doing apt-get install python-bottle and got the version:

```
In [1]: import bottle

In [2]: bottle.__version__
Out[2]: '0.10.6'
```

Maybe that has something to do. I'll keep trying.

**Comment by mani-monaj** [comment]
@awesomebytes Apparently `debug` was not an option for `bottle.run()` in version `0.10`. The fix is either to check the version prior to calling `run` or catch the exception and have a fallback mode with minimum number of params passed to `run`. I will implement latter pretty soon.
